version: "3.9"

services:
  content-service:
    container_name: sharp-translate
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=sharp-translate-db-dev;Username=postgres;Password=${SECRET_PASSWORD};Integrated Security=true;Pooling=true;"
      TranslationServiceUrl: "http://translation-service:5000/translate"
      AVAILABLE_LANGUAGES: ${AVAILABLE_LANGUAGES}
      ASPNETCORE_ENVIRONMENT: Development
      Serilog__MinimumLevel__Default: Information
      Serilog__MinimumLevel__Override__Microsoft: Information
      Serilog__MinimumLevel__Override__System: Warning
    ports:
      - "8080:80"
    depends_on:
      - postgres_db
      - translation-service
  
  translation-service:
    container_name: libretranslate
    image: libretranslate/libretranslate:v1.5.6
    restart: unless-stopped
    environment:
      LT_LOAD_ONLY: ${AVAILABLE_LANGUAGES}
      ARGOS_DEBUG: 1
    ports:
      - "5001:5000"
    depends_on:
      - postgres_db
    volumes:
      - ./libretranslate_cache_dev:/home/libretranslate/.local/share:z
  
  postgres_db:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SECRET_PASSWORD}
    ports:
      - "6001:5432"
    volumes:
      - ./db_dev:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana


  # elasticsearch:
  #   container_name: els
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
  #   restart: always
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - ./elasticsearch_data:/usr/share/elasticsearch/data
  #   environment:
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node

  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:8.7.1
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     - ELASTICSEARCH_URL=http://localhost:9200