version: "3.9"

services:
  content-service:
    container_name: sharp-translate
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=sharp-translate-db-dev;Username=postgres;Password=${SECRET_PASSWORD};Integrated Security=true;Pooling=true;"
      TranslationServiceUrl: "http://translation-service:5000/translate"
    ports:
      - "8080:80"
    depends_on:
      - postgres_db
      - translation-service
  
  translation-service:
    container_name: libretranslate
    image: libretranslate/libretranslate:v1.5.6
    environment:
      LT_LOAD_ONLY: "en,ru"
      ARGOS_DEBUG: 1
    ports:
      - "5001:5000"
    depends_on:
      - postgres_db
    volumes:
      - ../libretranslate_cache_dev:/home/libretranslate/.local/share:z
  
  postgres_db:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SECRET_PASSWORD}
    ports:
      - "6001:5432"
    volumes:
      - ../db_dev:/var/lib/postgresql/data