name: Docker Image CI
env:
  DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag ${{ env.DOCKERHUB_LOGIN }}/sharp-translate:latest
    - name: Login into DockerHub
      run: docker login -u ${{ env.DOCKERHUB_LOGIN }} -p ${{ env.DOCKERHUB_PASSWORD }}
    - name: Publish the docker image
      run: docker push -a ${{ env.DOCKERHUB_LOGIN }}/sharp-translate
